default_language_version:
  python: python3

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks
  autofix_prs: true
  autoupdate_branch: "master"
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: quarterly
  skip: []
  submodules: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-docstring-first
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: forbid-new-submodules
      - id: pretty-format-json
        args: ["--autofix", "--no-sort-keys", "--indent=4"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff
        args: ["--ignore=E402,E501,F401", "--fix"] #, --exit-non-zero-on-fix, ]
      - id: ruff
        name: ruff lint data notebooks
        args: ["--fix", "--preview", "--select=NPY201"]
      - id: ruff
        args: ["check", "--select", "I", "--fix"]
      - id: ruff-format
        types_or: [python, pyi, jupyter]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args:
          - --ignore-words-list=metadat,splitted,meaned,wil,whats,additionals,alle,alot,bund,currenty,datas,farenheit,falsy,fo,haa,hass,iif,incomfort,ines,ist,nam,nd,pres,pullrequests,resset,rime,ser,serie,te,technik,ue,unsecure,withing,zar,MAPE,mape
          - --skip="./.*,*.csv,*.json,*.ambr"
          - --quiet-level=2
        exclude_types: [csv, json]
        exclude: ^tests/|generated/^.github

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
        exclude: ^.github
