- name: BNCI2014_001
  test_path: ./data/moabb/BNCI2014_001_dl/train/
  num_rolls: 1
- name: BNCI2014_004
  test_path: ./data/moabb/BNCI2014_004_dl/train/
  num_rolls: 1
- name: BNCI2015_001
  test_path: ./data/moabb/BNCI2015_001_dl/train/
  num_rolls: 1
- name: Weibo2014
  test_path: ./data/moabb/Weibo2014_dl/train/
  num_rolls: 1
- name: Cho2017
  test_path: ./data/moabb/Cho2017_dl/train/
  num_rolls: 1
- name: Liu2024
  test_path: ./data/moabb/Liu2024_dl/train/
  num_rolls: 1
- name: PhysionetMI
  test_path: ./data/moabb/PhysionetMI_dl/train/
  num_rolls: 1
